include(FetchContent)
set(RAPIDJSON_BUILD_DOC OFF)
set(RAPIDJSON_BUILD_EXAMPLES OFF)
set(RAPIDJSON_BUILD_TESTS OFF)
set(RAPIDJSON_BUILD_CXX11 OFF)
set(RAPIDJSON_BUILD_CXX17 ON)
set(RAPIDJSON_HAS_STDSTRING ON)
FetchContent_Declare(
    RapidJSON
    GIT_REPOSITORY https://github.com/Tencent/rapidjson.git
    GIT_TAG        24b5e7a8b27f42fa16b96fc70aade9106cf7102f
    GIT_PROGRESS TRUE
    DOWLOAD_EXTRACT_TIMESTAMP TRUE
)
message("RapidJSON")
FetchContent_MakeAvailable(RapidJSON)